name: Release gekkoboot

on:
  push:
    tags:
      - 'r[0-9]+.[0-9]+' # Trigger on tags like r1.1, r9.2

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    permissions:
      contents: write # Required to create release and upload assets

    steps:
    - name: Install packages
      run: |
        apt-get update # Running as root in container, no sudo needed
        apt-get install -y --no-install-recommends build-essential python3-pip p7zip-full git # Need git for release.sh
        pip3 install meson

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Necessary for git describe in release.sh

    - name: Mark repository as safe
      run: git config --global --add safe.directory $GITHUB_WORKSPACE

    - name: Fetch Qoob prebuilt
      run: curl -Lo res/ipl.rom https://github.com/redolution/gekkoboot/releases/download/r5.2/iplboot.gcb

    - name: Run release script
      run: |
        export PATH="$DEVKITPPC/bin:$PATH"
        ./release.sh

    - name: Create GitHub Release and Upload Asset
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: gekkoboot ${{ github.ref_name }}
        draft: true
        prerelease: false
        files: ./gekkoboot-${{ github.ref_name }}.zip 
